
#---------------------------------------------- eureka slave2 注册中心配置 ----------------------------------------------------
server:
  port: 28761

spring:
  application:
    name: mss-server-eureka # 应用名称
  profiles: slave2 # 【eureka服务器集群 —— 节点2】 用于main方法启动的时候，用户需要输入的内容。标识启动的是哪一个eureka服务器；

eureka:
  instance:
    hostname: server.eureka.slave2.com # 服务所在主机（一般都是配置域名；本地测试的话，需要在 host 文件中指定虚拟域名
  client:
    service-url:
      defaultZone: http://server.eureka.slave1.com:18761/eureka,http://server.eureka.slave2.com:28761/eureka # eureka服务器的地址
    fetch-registry: false # 获取注册列表
    register-with-eureka: true # 是否将自己也注册到其他eureka节点上。一般设置为true或者默认即可，这样才会在eureka控制台上看到所有的eureka集群列表信息


