server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://10.89.36.152:3306/mss?&characterEncoding=utf-8&useSSL=false #数据库的连接信息
    driver-class-name: com.mysql.jdbc.Driver #数据库驱动
    username: dev #数据库的用户名
    password: yfzx@2019 #数据库的密码
  #jpa配置
  jpa:
    database: mysql #数据库类型
    show-sql: true #是否在控制台答应sql
    hibernate:
      ddl-auto: update #可选项:none、create、create-drop、update、validate
        #      naming:
      #下面的配置为关闭驼峰转下划线命名规则，不配置该项，默认为开启状态
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #数据库方言
    properties:
      hibernate:
        format_sql: true #是否格式化sql

#springdoc:
#  swagger-ui:
#    path: /api-docs.html
#  packagesToScan: mss.service.user.controller